# Our Process {-#our-process}

Below we'll detail how we created this awesome website!

## Setting up R-Markdown project {-#setting-up-r-markdown-project}

[Video on how to set up bookdown project](https://www.youtube.com/watch?v=RdSmYvbQkhs&ab_channel=GregoryMacfarlane)

I followed the above tutorial to create the bookdown page below

[Cool help guide on bookdown styling](https://rstudio4edu.github.io/rstudio4edu-book/index.html)


[Good resource for bs4_book](https://bookdown.org/yihui/bookdown/html.html)


## GitHub {-#github}

connected to git hub

insert tutorial later

we made sure everyone could push and pull.  we encountered issues but resolved them by communicating or using the following git commands:

## Content Sections {-#content-sections}

### About Us {-#about-us}

1. This section contains the introduction of our team members and our LinkedIn links if users want to contact our team members or learn more about us.

2. We built a csv file, uploaded it to our Google drive, and asked everyone to fill in the blanks. The contents are the following:
+ **Title**: Our names in alphabetical order.
+ **Text**: Brief introduction of ourselves. It contains our education background, our internship and working experience, and our vision in the future.
+ **Link**: Our LinkedIn personal URL so that users could see our member's personal file.
+ **Image**: Our member's photo stickers. All of us are very handsome, right?

3. After finishing our csv file, we would download it into our computer and use R language in R studio to let it read our file.

4. Finally, we would install package in "Build", commit, and push to the github.

### Potential Careers {-#potential-careers}

We chose five potential careers that are the most related to the BA program: Data Scientist, Data Engineer, Business Analyst, Data Analyst and BI Engineer. Each member on the team takes one career to do deep research. 

We created an excel to put all of the career information such as open roles, salaries and preferred skills in. This csv file will then be added to our resource. We then created a template to show each career clearly. This saved us a lot of lines of codes. Bootstrap cards are also used in this section for open roles which users are able to see it more clearly visually and have the links directly to the job website. 

### Other Programs {-#other-programs}

We chose around ten schools' BA programs which we believe are similar to our program. We found their curriculum, courses, tuition, ranking and other general information for the schools and employment data if there is any. We also put all these data into the csv file for us to change and insert easily. One feature we used in the R in this section is hide and unhide. This makes the website look clean and users can choose the schools they are interested on their own. The employment data for each school is also directly linked. 

### Salary Expectations {-#salary-expectations}

talk about ggplot and manipulating dataframes

### Company Database {-#company-database}

talk about webscraping and python and glassdoor

### Resources {-#resources}

1. This section contains the introduction of data processing skills and languages which are widely used in data analysis positions and useful links to learn them especially for beginners.

2. According to possible careers and MBAn curriculum, we understood the requirements and preferences of Business Analytics related positions. Then, we summarized some important programming and software skills which were Python, SQL, Excel, R, and other Business Intelligence Tools.

3. We wrote about each module in three parts:
+ **Summary**: Briefly introduce what is the skill and what does it use for.
+ **Customers**: The companies which extensively use such skill during their work.
+ **Ways to Learn**: We told how could they build the environment by downloading software and language package. Also, we recommended useful learning resources such as Coursera, YouTube, library, and documents.

4. To finish this section. We used some R Markdown Syntax:
+ Insert links in words or sentences: [words or sentences](links)
+ Bold subtitles: **subtitle**
+ Ballpoints: -

### Deploying Site {-#deploying-site}

When we push to github we set up github pages to automatically deploy the site with the most recent changes.  Provide link to how to set this up

## Team Strategy {-#team-strategy}

We are the 007 Wolverines

### Handling Changes and Conflict {-#handling-changes-and-conflict}

we used class content

### Dividing Work {-#dividing-work}

Our team was able to finalize the website structure and different sections we want to include very early. This allowed us to have the project timeline ready very early, too. Basically for each week, our week focused on completing on section. Inside the section, we divided our work either at the team meeting or sign up on a separate spreadsheet. Luckily, all of our team members kept up with the deadline very well. We reminded and helped each other for any technical or research difficulties. Therefore, an additional section was required by Sanjeev at the end of the semester, we managed to push the deadline a little bit early and finished the whole project on time. 


### Agile {-#agile}

* Before we hold a meeting, we would briefly introduce the main purpose, some bull-points, and some points of note of the meeting. If it involves our previous work, we will check if everyone has done. Also, we check everyone's schedule to ensure everyone could attend the meeting. We need to increase the participation rate and let all members understand our project and process comprehensively to narrow the information gap so we could push our project with great efficiency.

* During the meeting, everyone is welcomed to express their opinions and exchange ideas. When someone is talking about our project, others are listening to him carefully and respectfully. For someone giving thoughtful ideas, we show high recommendation to him. If he ignores something, we would remind him instead of blaming him. We maintain a healthy and positive atmosphere in our team so that everyone feels comfortable in the team.

* At the end of the meeting, our leader quickly makes the decision about our next step, what we should do, and our deadline of our tasks. Because of fully preparation before the meeting and active discussion during the meeting, we easily come to agreement so that we could speed up our decision process and leave time for feedback.

* Not only do we focus on our project, but we pay attention to personal development. Our team leader always teaches us some useful tools in R Markdown and how to use them.

## Final Thoughts {-#final-thoughts}

* Overall we all believe this is an excellent team project experience. Grant is very experienced in doing this type of work and he has been a great team leader. Everybody else has also been learning so much from him as well as finishing his own work efficiently. This is a valuable lesson for each of us to gain some new skills by working on a team programming project. 

* In the remaining time, all we have left is the final presentation for this project. This is an exciting time for us to share what we created and how other students could use it as a helpful resource in the future. We will keep using our team operation strategy to prepare for the presentation. We will also try to change things we hoped to improve according to the mid point report. All in all, we want to finish this semester strongly with the presentation. 